### Create Person default transaction
POST http://localhost:4004/catalog/createPersonDefaultTx HTTP/1.1
Content-Type:  application/json
Authorization: Basic sam:sam

{
    "person":{
        "name":"sam_createPersonDefaultTx"
    }
}

### Create Person get manually the default transaction
POST http://localhost:4004/catalog/createPersonOk HTTP/1.1
Content-Type:  application/json
Authorization: Basic sam:sam

{
    "person":{
        "name":"sam_createPersonOk"
    }
}

### Crash Person because of entity already exists, crash CAP
POST http://localhost:4004/catalog/createPersonCrash HTTP/1.1
Content-Type:  application/json
Authorization: Basic sam:sam

{
    "person":{
        "name":"sam"
    }
}

### Many transactions
POST http://localhost:4004/catalog/createPersonsManyTransactions HTTP/1.1
Content-Type:  application/json
Authorization: Basic sam:sam

{
    "persons": [
        {
            "name": "sam1"
        },
        {
            "name": "sam2"
        },
        {
            "name": "sam1"
        },
        {
            "name": "sam3"
        }
    ]
}


### Many cstom transactions
POST http://localhost:4004/catalog/createPersonsCustomTransactions HTTP/1.1
Content-Type:  application/json
Authorization: Basic sam:sam

{
    "persons": [
        {
            "name": "sam1_createPersonsCustomTransactions"
        },
        {
            "name": "sam2_createPersonsCustomTransactions"
        },
        {
            "name": "sam1_createPersonsCustomTransactions"
        },
        {
            "name": "sam3_createPersonsCustomTransactions"
        }
    ]
}

### 
GET http://localhost:4004/catalog/Persons HTTP/1.1
Authorization: Basic sam:sam